import type { AlphaRadarTrackedFilerInput } from '../validators/alpha-radar';

export const ALPHA_RADAR_SEED_FILERS: AlphaRadarTrackedFilerInput[] = [
    {
        name: 'Berkshire Hathaway Inc',
        slug: 'berkshire-hathaway',
        cik: '0001067983',
        secEntityName: 'BERKSHIRE HATHAWAY INC',
        managerName: 'Warren Buffett',
        fundStyle: 'quality-value',
        enabled: true,
        notes: 'Concentrated long-term value and quality compounder benchmark.',
    },
    {
        name: 'Bridgewater Associates, LP',
        slug: 'bridgewater-associates',
        cik: '0001350694',
        secEntityName: 'BRIDGEWATER ASSOCIATES, LP',
        managerName: 'Ray Dalio',
        fundStyle: 'macro',
        enabled: true,
        notes: 'Macro-oriented institutional manager useful for broad risk-on/risk-off reads.',
    },
    {
        name: 'Altimeter Capital Management, LP',
        slug: 'altimeter-capital',
        cik: '0001541617',
        secEntityName: 'ALTIMETER CAPITAL MANAGEMENT, LP',
        managerName: 'Brad Gerstner',
        fundStyle: 'growth-tech',
        enabled: true,
        notes: 'Public/private growth manager with useful cloud, travel, and AI infrastructure exposure.',
    },
    {
        name: 'Coatue Management LLC',
        slug: 'coatue-management',
        cik: '0001135730',
        secEntityName: 'COATUE MANAGEMENT LLC',
        managerName: 'Philippe Laffont',
        fundStyle: 'growth-tech',
        enabled: true,
        notes: 'Technology-focused manager useful for consensus growth and AI infrastructure reads.',
    },
    {
        name: 'ARK Investment Management LLC',
        slug: 'ark-investment-management',
        cik: '0001697748',
        secEntityName: 'ARK INVESTMENT MANAGEMENT LLC',
        managerName: 'Cathie Wood',
        fundStyle: 'disruptive-growth',
        enabled: true,
        notes: 'High-beta innovation manager useful for thematic growth and disruption watchlists.',
    },
    {
        name: 'Pershing Square Capital Management, L.P.',
        slug: 'pershing-square',
        cik: '0001336528',
        secEntityName: 'PERSHING SQUARE CAPITAL MANAGEMENT, L.P.',
        managerName: 'Bill Ackman',
        fundStyle: 'concentrated-activist',
        enabled: true,
        notes: 'Concentrated activist/value manager useful for high-conviction idea tracking.',
    },
];
